<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" total="3" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Regression" duration-ms="28640" started-at="2020-04-22T21:36:00Z" finished-at="2020-04-22T21:36:29Z">
    <groups>
      <group name="Regression">
        <method signature="LoginTestWithDataProvider.verifyUserShouldNavigateToLoginPage(java.lang.String, java.lang.String)[pri:0, instance:com.demo.nopcommerce.testsuit.LoginTestWithDataProvider@234bef66]" name="verifyUserShouldNavigateToLoginPage" class="com.demo.nopcommerce.testsuit.LoginTestWithDataProvider"/>
        <method signature="RegisterTestWithDataProvider.verifyUserShouldRegisterSuccessfully()[pri:0, instance:com.demo.nopcommerce.testsuit.RegisterTestWithDataProvider@7c0e2abd]" name="verifyUserShouldRegisterSuccessfully" class="com.demo.nopcommerce.testsuit.RegisterTestWithDataProvider"/>
        <method signature="ComputersTest.verifyUserCanAddToShoppingCart()[pri:0, instance:com.demo.nopcommerce.testsuit.ComputersTest@7ac7a4e4]" name="verifyUserCanAddToShoppingCart" class="com.demo.nopcommerce.testsuit.ComputersTest"/>
      </group> <!-- Regression -->
      <group name="smoke">
        <method signature="RegisterTestWithDataProvider.verifyUserShouldRegisterSuccessfully()[pri:0, instance:com.demo.nopcommerce.testsuit.RegisterTestWithDataProvider@7c0e2abd]" name="verifyUserShouldRegisterSuccessfully" class="com.demo.nopcommerce.testsuit.RegisterTestWithDataProvider"/>
      </group> <!-- smoke -->
      <group name="sanity">
        <method signature="ComputersTest.verifyUserCanAddToShoppingCart()[pri:0, instance:com.demo.nopcommerce.testsuit.ComputersTest@7ac7a4e4]" name="verifyUserCanAddToShoppingCart" class="com.demo.nopcommerce.testsuit.ComputersTest"/>
      </group> <!-- sanity -->
    </groups>
    <test name="Login Test" duration-ms="19" started-at="2020-04-22T21:36:00Z" finished-at="2020-04-22T21:36:00Z">
      <class name="com.demo.nopcommerce.testsuit.LoginTestWithDataProvider">
        <test-method status="FAIL" signature="verifyUserShouldNavigateToLoginPage(java.lang.String, java.lang.String)[pri:0, instance:com.demo.nopcommerce.testsuit.LoginTestWithDataProvider@234bef66]" name="verifyUserShouldNavigateToLoginPage" duration-ms="0" started-at="2020-04-22T22:36:00Z" data-provider="LoginData" finished-at="2020-04-22T22:36:00Z">
          <exception class="org.testng.TestNGException">
            <message>
              <![CDATA[
Method public void com.demo.nopcommerce.testsuit.LoginTestWithDataProvider.verifyUserShouldNavigateToLoginPage(java.lang.String,java.lang.String) requires a @DataProvider named : LoginData in class com.demo.nopcommerce.testData.TestData]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestNGException: 
Method public void com.demo.nopcommerce.testsuit.LoginTestWithDataProvider.verifyUserShouldNavigateToLoginPage(java.lang.String,java.lang.String) requires a @DataProvider named : LoginData in class com.demo.nopcommerce.testData.TestData
	at org.testng.internal.Parameters.findDataProvider(Parameters.java:268)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:417)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1383)
	at org.testng.internal.Invoker.createParameters(Invoker.java:1075)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1180)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:110)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestNGException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyUserShouldNavigateToLoginPage -->
      </class> <!-- com.demo.nopcommerce.testsuit.LoginTestWithDataProvider -->
    </test> <!-- Login Test -->
    <test name="Register Test" duration-ms="15266" started-at="2020-04-22T21:36:00Z" finished-at="2020-04-22T21:36:16Z">
      <class name="com.demo.nopcommerce.testsuit.RegisterTestWithDataProvider">
        <test-method status="PASS" signature="openBrowser()[pri:0, instance:com.demo.nopcommerce.testsuit.RegisterTestWithDataProvider@7c0e2abd]" name="openBrowser" is-config="true" duration-ms="14421" started-at="2020-04-22T22:36:00Z" finished-at="2020-04-22T22:36:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openBrowser -->
        <test-method status="FAIL" signature="verifyUserShouldRegisterSuccessfully()[pri:0, instance:com.demo.nopcommerce.testsuit.RegisterTestWithDataProvider@7c0e2abd]" name="verifyUserShouldRegisterSuccessfully" duration-ms="4" started-at="2020-04-22T22:36:15Z" finished-at="2020-04-22T22:36:15Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.demo.nopcommerce.testsuit.RegisterTestWithDataProvider.verifyUserShouldRegisterSuccessfully(RegisterTestWithDataProvider.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:110)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyUserShouldRegisterSuccessfully -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.demo.nopcommerce.testsuit.RegisterTestWithDataProvider@7c0e2abd]" name="tearDown" is-config="true" duration-ms="799" started-at="2020-04-22T22:36:15Z" finished-at="2020-04-22T22:36:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.demo.nopcommerce.testsuit.RegisterTestWithDataProvider -->
    </test> <!-- Register Test -->
    <test name="Computer Test" duration-ms="13306" started-at="2020-04-22T21:36:16Z" finished-at="2020-04-22T21:36:29Z">
      <class name="com.demo.nopcommerce.testsuit.ComputersTest">
        <test-method status="PASS" signature="openBrowser()[pri:0, instance:com.demo.nopcommerce.testsuit.ComputersTest@7ac7a4e4]" name="openBrowser" is-config="true" duration-ms="12477" started-at="2020-04-22T22:36:16Z" finished-at="2020-04-22T22:36:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openBrowser -->
        <test-method status="FAIL" signature="verifyUserCanAddToShoppingCart()[pri:0, instance:com.demo.nopcommerce.testsuit.ComputersTest@7ac7a4e4]" name="verifyUserCanAddToShoppingCart" duration-ms="1" started-at="2020-04-22T22:36:28Z" finished-at="2020-04-22T22:36:28Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.demo.nopcommerce.testsuit.ComputersTest.verifyUserCanAddToShoppingCart(ComputersTest.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:110)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyUserCanAddToShoppingCart -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.demo.nopcommerce.testsuit.ComputersTest@7ac7a4e4]" name="tearDown" is-config="true" duration-ms="825" started-at="2020-04-22T22:36:28Z" finished-at="2020-04-22T22:36:29Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.demo.nopcommerce.testsuit.ComputersTest -->
    </test> <!-- Computer Test -->
  </suite> <!-- Regression -->
</testng-results>
